version: '2'
services:
  server:
    container_name: todo-app
    image: 11me/todo-app:v2
    restart: unless-stopped
    environment:
      PG_HOST: postgres
      PG_PASSWORD: mysecretpassword
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
