apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo
        image: 11me/todo-app:v3
        ports:
        - containerPort: 3001
        env:
        - name: SERVICE_PORT
          value: '8080'
        - name: PG_HOST
          value: postgres
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: pg_password
